# Generated by Django 4.1.4 on 2022-12-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0002_rename_frist_ame_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateadd',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedRea', to='mainbdd.user'),
        ),
    ]
