# Generated by Django 4.1.4 on 2022-12-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0004_alter_offer_offerer_alter_offer_real_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='mainbdd.user'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerers', to='mainbdd.realestateadd'),
        ),
    ]
