# Generated by Django 4.1.4 on 2022-12-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0006_alter_offer_real_estate_alter_realestateadd_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateadd',
            name='surface',
            field=models.FloatField(null=True),
        ),
    ]
