# Generated by Django 4.1.4 on 2022-12-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0007_alter_realestateadd_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateadd',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
