# Generated by Django 4.1.4 on 2022-12-25 19:30

from django.db import migrations, models
import mainbdd.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0008_alter_realestateadd_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='posts/default.jpg', upload_to=mainbdd.models.upload_to)),
            ],
        ),
    ]
