# Generated by Django 4.1.4 on 2022-12-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0009_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='rea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mainbdd.realestateadd'),
        ),
    ]
