# Generated by Django 4.1.4 on 2022-12-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0011_profile_alter_photo_rea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
