# Generated by Django 4.1.4 on 2022-12-26 14:11

from django.db import migrations, models
import django.db.models.deletion
import mainbdd.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0012_delete_photo_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='posts/default.jpg', upload_to=mainbdd.models.upload_to)),
                ('rea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mainbdd.realestateadd')),
            ],
        ),
    ]
