# Generated by Django 4.1.4 on 2022-12-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbdd', '0021_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateadd',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='realestateadd',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
